[package]
name = "forward"
version = "0.1.0"
authors = ["Prusti Devs <prusti_developers@sympa.ethz.ch>"]
edition = "2021"

[dependencies]
prusti-rustc-interface = { path = "/Users/zgrannan/prusti-dev/prusti-rustc-interface" }
